//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageRepo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Images_Table
    {
        public int Id { get; set; }
        public string Img_Filename { get; set; }
        public string Caption_Text { get; set; }
    }
}
