//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sjghel_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donation
    {
        public int Id { get; set; }
        public System.DateTime Donation_Date { get; set; }
        public int Donor_Id { get; set; }
        public decimal Amount { get; set; }
        public string Message { get; set; }
        public string Payment_API { get; set; }
        public string Payment_Method { get; set; }
    
        public virtual Donor Donor { get; set; }
    }
}
