//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sjghel_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int news_id { get; set; }
        public System.DateTime news_post_time { get; set; }
        public System.DateTime news_edit_time { get; set; }
        public string news_title { get; set; }
        public string news_brief { get; set; }
        public string news_content { get; set; }
        public string news_pic_path { get; set; }
    }
}
