//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sjghel_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Testimonial
    {
        public int testimonial_id { get; set; }
        public string testimonial_title { get; set; }
        public string testimonial_description { get; set; }
        public string patient_name { get; set; }
        public string testimonial_image { get; set; }
        public bool is_published { get; set; }
    }
}
