//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace anythingProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sjghel_patients
    {
        public int patient_id { get; set; }
        public string patient_email { get; set; }
        public string patient_password { get; set; }
        public string patient_first_name { get; set; }
        public string patient_last_name { get; set; }
        public System.DateTime patient_date_of_birth { get; set; }
        public string patient_gender { get; set; }
        public string patient_phone { get; set; }
        public string patient_address { get; set; }
        public string patient_postcode { get; set; }
    }
}
